set -g mouse on
setw -g mode-keys vi
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "sh -lc 'wl-copy --foreground'"

##### Enable 256 color + truecolor
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",*:Tc"

##### Status bar base
set -g status-style bg=colour235,fg=colour153
set -g status-interval 5
set -g status-justify centre

##### Left side (session name)
set -g status-left-length 40
set -g status-left "#[fg=colour231,bg=colour31,bold] ❄  #S #[fg=colour31,bg=colour235,nobold]"

##### Right side (time/date)
set -g status-right-length 50
set -g status-right "#[fg=colour31,bg=colour235]#[fg=colour231,bg=colour31] %H:%M:%S ❄ %d %b "

##### Window tabs (inactive)
set -g window-status-format " #[fg=colour109]#I:#W "

##### Active window tab
set -g window-status-current-format "#[fg=colour231,bg=colour39,bold]  #I:#W "
##### Pane borders
set -g pane-border-style fg=colour238
set -g pane-active-border-style fg=colour39

##### Message styling
set -g message-style bg=colour31,fg=colour231

##### Mode (copy mode etc.)
set -g mode-style bg=colour39,fg=colour231

