background {
    path = ~/dotfiles/perrinwallpaper.jpg
    blur_passes = 2
    blur_size = 6
}

input-field {
    size = 300, 60
    outline_thickness = 3
    dots_size = 0.3
    dots_spacing = 0.2
    dots_center = true

    outer_color = rgba(ff5a36ff)
    inner_color = rgba(1a1a1aff)
    font_color = rgba(ff884dff)

    position = 0, -80
    halign = center
    valign = center
}

label {
    text = cmd[update:1000] date "+%H:%M:%S"
    color = rgba(ff884dff)
    font_size = 60
    position = 0, 0
    halign = center
    valign = center
}
label {
    text = cmd[update:60000] date "+%A, %d %B %Y"
    font_size = 18
    color = rgba(ffb347ff)
    position = 0, 60
    halign = center
    valign = center
}

label {
    text = cmd[update:10] sh -c "cat /sys/class/power_supply/BAT0/capacity 2>/dev/null | sed 's/$/%/'"
    font_size = 16
    color = rgba(ff5a36ff)
    position = 0, 100
    halign = center
    valign = center
}
